id: PB35A1867
initial_creation_type: input
source_metadata:
  title: Drukpa Kunley Series
  language: bo
  description: 'Texts by and about the controversial yogi and self-proclaimed ''madman''
    Drukpa Kunga Lekpa (''brug pa kun dga'' legs pa, 1455–1529), popularly known as
    Drukpa Kunley:'
  volume:
    ac83554414234846a8bed90287bfacee:
      title: Prayer to Drukpa Kunley
      parent: Prayers
created_at: '2022-02-28T23:05:39.878654'
last_modified_at: '2022-02-28T23:05:39.878656'
